### ISSUE TITLE
client.ResolvePeer 

### ISSUE THREAD

**Issue by pd5200** [AmarnathCJD/gogram#130]
The client.ResolvePeer(chatid) function sometimes gets stuck. I'm not sure what the cause is. Restarting sometimes resolves the issue. This problem is not easy to reproduce. Please help investigate whether there is a locking issue.

If I find a solution, I will get back to you. If you find one, please let me know. Thank you.

**Comment by AmarnathCJD** [comment]
alright

**Comment by AmarnathCJD** [comment]
Issue with cache sync Locks?

**Comment by eos175** [comment]
In fact, the cache might have concurrency issues. The `update` methods use a mutex, but the access methods do not have a mutex

```go

func (c *CACHE) UpdateUser(user *UserObj) bool {
	c.Lock()
	defer c.Unlock()

	if currAccessHash, ok := c.InputPeers.InputUsers[user.ID]; ok {
		if currAccessHash != user.AccessHash {
			c.InputPeers.InputUsers[user.ID] = user.AccessHash
			c.users[user.ID] = user
			return true
		}
		return false
	}

	c.users[user.ID] = user
	c.InputPeers.InputUsers[user.ID] = user.AccessHash

	return true
}
--------------
func (c *Client) GetPeerUser(userID int64) (*InputPeerUser, error) {
	if peer, ok := c.Cache.InputPeers.InputUsers[userID]; ok {
		return &InputPeerUser{UserID: userID, AccessHash: peer}, nil
	}
	return nil, fmt.Errorf("no user with id %d or missing from cache", userID)
}
```

**Comment by AmarnathCJD** [comment]
@eos175 how about the locks now?
😂😂

Locks are pain, I never learned them

**Comment by eos175** [comment]
yes, it looks good

**Comment by eos175** [comment]
How about using an interface for the cache `InputPeers *InputPeerCache`, something like:
```go
type CacheStorage interface {
    Set(key, value uint64) error
    Get(key uint64) (uint64, error)
    Delete(key uint64) error
}
```
and store everything in the same storage. According to the Telegram documentation, user_id, chat_id, and channel_id use [52 bits](https://core.telegram.org/bots/api#contact)

leaving 12 bits to store typeID, and the sign in two's complement. For example:
```go
const (
	TypeChat    = iota + 1 // 1
	TypeUser               // 2
	TypeChannel            // 3
)
```

The advantage is that any key-value storage, like Redis, could be used...

The storage would also be simpler because there would be no need to store `1:%d:%d`, instead, we write binary with `binary.LittleEndian.PutUint64` or let the storage handle that.

**Comment by AmarnathCJD** [comment]
w
